// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkQhiPBXhPK6UJEteJq1vfi-fw-nlEgzA',
    appId: '1:296074142437:web:a64427eec89b907c96aa0c',
    messagingSenderId: '296074142437',
    projectId: 'chat-app-737da',
    authDomain: 'chat-app-737da.firebaseapp.com',
    storageBucket: 'chat-app-737da.firebasestorage.app',
    measurementId: 'G-MHM3YR22VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOwugUM5mHY7tAFZBIvQpVZNWP6_XVhDM',
    appId: '1:296074142437:android:ccc689f6c40b2c5096aa0c',
    messagingSenderId: '296074142437',
    projectId: 'chat-app-737da',
    storageBucket: 'chat-app-737da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSmhIsTSJGSKCKvd5c6IV71Ae4h3Lb90',
    appId: '1:296074142437:ios:3ebd475ffd05b06f96aa0c',
    messagingSenderId: '296074142437',
    projectId: 'chat-app-737da',
    storageBucket: 'chat-app-737da.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSmhIsTSJGSKCKvd5c6IV71Ae4h3Lb90',
    appId: '1:296074142437:ios:3ebd475ffd05b06f96aa0c',
    messagingSenderId: '296074142437',
    projectId: 'chat-app-737da',
    storageBucket: 'chat-app-737da.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkQhiPBXhPK6UJEteJq1vfi-fw-nlEgzA',
    appId: '1:296074142437:web:f9be3d93938bf19b96aa0c',
    messagingSenderId: '296074142437',
    projectId: 'chat-app-737da',
    authDomain: 'chat-app-737da.firebaseapp.com',
    storageBucket: 'chat-app-737da.firebasestorage.app',
    measurementId: 'G-FP64B2PH9W',
  );
}
